### ISSUE TITLE
Build out module pages

### ISSUE THREAD

**Issue by anthonyvalera** [anthonyvalera/smdi#11]
Tasklist:

- [x] Module Styles
- [x] Clean up HTML
  - [x] Module 1
  - [x] Module 2
  - [x] Module 3
  - [x] Module 4
  - [x] Module 5
  - [x] Module 6
  - [x] Module 7
  - [x] Module 8
  - [x] Module 9
- [x] Module Edits

**Comment by bryonlehl** [comment]
Module 1 Ready For Review

**Comment by bryonlehl** [comment]
Module 2 and 3 ready for Review

**Comment by anthonyvalera** [comment]
Looks good
